### ISSUE TITLE
Unable to migrate Serverless function that references CodeUri S3 bucket

### ISSUE THREAD

**Issue by steven10172** [cdklabs/cdk-from-cfn#693]
When trying to migrate the following Serverless construct it failed with an error. Converting `CodeUri` to a string resolved the error and the migrate command continued as expected.

Construct:
```
  CheckMinimumCLIVersionLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket:
          Fn::Sub: ${S3BucketName}
        Key:
          Fn::Sub: ${S3KeyName}
      Handler: dist/admin/check-cli-version.handler
      MemorySize: 512
      Role:
        Fn::GetAtt: [CheckMinimumCLIVersionLambdaRole, Arn]
      Runtime: nodejs16.x
      Timeout: 60
      AutoPublishAlias: live
      Environment:
        Variables:
          ACCOUNT_ID:
            Ref: AWS::AccountId
          MASTER_REGION:
            Fn::Sub: ${MasterAccountRegion}
```

Error:
```
MyStack could not be generated because Some(Union(Static([Primitive(String), Named("AWS::Serverless::Function.S3Location")]))) is not implemented for ResourceValue::Object
```
