### ISSUE TITLE
Bug: WarmThroughput unrecognized as a valid property of AWS::DynamoDB::Table

### ISSUE THREAD

**Issue by fibert** [cdklabs/cdk-from-cfn#919]
When trying to use `cdk migrate` with a _WarmThroughput_ attribute the migration fails with the following error:

```
 ❌  Migrate failed for `[Name]`: [Name]Stack could not be generated because WarmThroughput is not a valid property for resource DynamoDBTableResumesitedevvisitorcount of type AWS::DynamoDB::Table
```

CDK's CfnTable supports [WarmThroughput](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.CfnTable.html#warmthroughput).

When deleting this attribute, the migration is successful

---

My CloudFormation template was generate by CloudFormation IaC Generator, and contains the following:

```
  DynamoDBTableResumesitedevvisitorcount:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: "resume-site-dev-visitor-count"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "id"
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
        RecoveryPeriodInDays: 35
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "id"
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      DeletionProtectionEnabled: false
      Tags:
      - Value: "dev"
        Key: "Environment"
      - Value: "Resume-Site"
        Key: "Project"
      - Value: "Terraform"
        Key: "ManagedBy"
      TimeToLiveSpecification:
        Enabled: false
```
