### ISSUE TITLE
Bug: RecursiveLoop unrecognized as a valid property of AWS::Lambda::Function

### ISSUE THREAD

**Issue by fibert** [cdklabs/cdk-from-cfn#920]
When trying to use `cdk migrate` with n _RecursiveLoop_ attribute the migration fails with the following error:

```
 ❌  Migrate failed for `[Name]`: [Name]Stack could not be generated because RecursiveLoop is not a valid property for resource LambdaFunctionResumesitedevapi of type AWS::Lambda::Function
```

CDK's CfnFunction supports [RecursiveLoop](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.CfnFunction.html#recursiveloop).

When deleting this attribute, the migration is successful

---

My CloudFormation template was generate by CloudFormation IaC Generator, and contains the following:

```
  LambdaFunctionResumesitedevapi:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 10
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3ObjectVersion:
          Ref: "LambdaFunctionResumesitedevapiCodeS3ObjectVersionocuPq"
        S3Bucket:
          Ref: "LambdaFunctionResumesitedevapiCodeS3BucketwOlVB"
        ZipFile:
          Ref: "LambdaFunctionResumesitedevapiCodeZipFileXIPwe"
        ImageUri:
          Ref: "LambdaFunctionResumesitedevapiCodeImageUriQgg2o"
        S3Key:
          Ref: "LambdaFunctionResumesitedevapiCodeS3Keym4c8Y"
      Role:
        Fn::GetAtt:
        - "IAMRoleResumesitedevapirole"
        - "Arn"
      FileSystemConfigs: []
      FunctionName: "resume-site-dev-api"
      Runtime: "python3.9"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/resume-site-dev-api"
      RecursiveLoop: "Terminate"
      Environment:
        Variables:
          DYNAMODB_TABLE: "resume-site-dev-visitor-count"
      EphemeralStorage:
        Size: 512
      Tags:
      - Value: "Resume-Site"
        Key: "Project"
      - Value: "Terraform"
        Key: "ManagedBy"
      - Value: "dev"
        Key: "Environment"
      Architectures:
      - "x86_64"
```
